### ISSUE TITLE
Complexity is n^m, should be n+m

### ISSUE THREAD

**Issue by vitalk** [temp-rw/LeverX-Python-HT#5]
https://github.com/temp-rw/LeverX-Python-HT/blob/ba7bbbc046bdf6478f2a0db214ec77e27653cf5b/Task1/main.py#L30

**Comment by temp-rw** [comment]
Fixed by adding else statement and using sorted list of students

**Comment by temp-rw** [comment]
Fixed by mapping students data to dictionary with room key instead of list.
